export const DRAWER_MENU_LABEL = {
  DASHBOARD: 'DASHBOARD',
  DEMO: 'DEMO',
  USER: 'USER',
  USER_LIST: 'USER_LIST',
  USER_ADD: 'USER_ADD',
  PLAY_BACKGROUND: 'PLAY_BACKGROUND',
  POST: 'POST',
  POST_ADD: 'POST_ADD',
  POST_LIST: 'POST_LIST',
  SHARING: 'SHARING',
  SHARING_ADD: 'SHARING_ADD',
  SHARING_LIST: 'SHARING_LIST',
};
